export const TTLockRecordStatus = [
   { id: 1, name: "unlock by app" },
   { id: 4, name: "unlock by passcode" },
   { id: 5, name: "Rise the lock (for parking lock)" },
   { id: 6, name: "Lower the lock (for parking lock)" },
   { id: 7, name: "unlock by IC card" },
   { id: 8, name: "unlock by fingerprint" },
   { id: 9, name: "unlock by wrist strap" },
   { id: 10, name: "unlock by Mechanical key" },
   { id: 11, name: "lock by app" },
   { id: 12, name: "unlock by gateway" },
   { id: 29, name: "apply some force on the Lock" },
   { id: 30, name: "Door sensor closed" },
   { id: 31, name: "Door sensor open" },
   { id: 32, name: "open from inside" },
   { id: 33, name: "lock by fingerprint" },
   { id: 34, name: "lock by passcode" },
   { id: 35, name: "lock by IC card" },
   { id: 36, name: "lock by Mechanical key" },
   {
      id: 37,
      name: "Use APP button to control the lock (rise, fall, stop, lock), mostly used for roller shutter door",
   },
   { id: 42, name: "received new local mail" },
   { id: 43, name: "received new other cities' mail" },
   { id: 44, name: "Tamper alert" },
   { id: 45, name: "Auto Lock" },
   { id: 46, name: "unlock by unlock key" },
   { id: 47, name: "lock by lock key" },
   {
      id: 48,
      name: "System locked (Caused by, for example: Using INVALID Passcode/Fingerprint/Card several times)",
   },
   { id: 49, name: "unlock by hotel card" },
   { id: 50, name: "Unlocked due to the high temperature" },
   { id: 51, name: "Try to unlock with a deleted card" },
   { id: 52, name: "Dead lock with APP" },
   { id: 53, name: "Dead lock with passcode" },
   { id: 54, name: "The car left (for parking lock)" },
   { id: 55, name: "Use remote control lock or unlock lock" },
   { id: 57, name: "Unlock with QR code success" },
   { id: 58, name: "Unlock with QR code failed, it's expired" },
   { id: 59, name: "Double locked" },
   { id: 60, name: "Cancel double lock" },
   { id: 61, name: "Lock with QR code success" },
   { id: 62, name: "Lock with QR code failed, the lock is double locked" },
   { id: 63, name: "Auto unlock at passage mode" },
   { id: 64, name: "Door unclosed alarm" },
   { id: 65, name: "Failed to unlock" },
   { id: 66, name: "Failed to lock" },
   { id: 67, name: "Face unlock success" },
   { id: 68, name: "Face unlock failed - door locked from inside" },
   { id: 69, name: "Lock with face" },
   { id: 71, name: "Face unlock failed - expired or ineffective" },
   { id: 75, name: "Unlocked by App granting" },
   { id: 76, name: "Unlocked by remote granting" },
   {
      id: 77,
      name: "Dual authentication Bluetooth unlock verification success, waiting for second user",
   },
   {
      id: 78,
      name: "Dual authentication password unlock verification success, waiting for second user",
   },
   {
      id: 79,
      name: "Dual authentication fingerprint unlock verification success, waiting for second user",
   },
   {
      id: 80,
      name: "Dual authentication IC card unlock verification success, waiting for second user",
   },
   {
      id: 81,
      name: "Dual authentication face card unlock verification success, waiting for second user",
   },
   {
      id: 82,
      name: "Dual authentication wireless key unlock verification success, waiting for second user",
   },
   {
      id: 83,
      name: "Dual authentication palm vein unlock verification success, waiting for second user",
   },
   { id: 84, name: "Palm vein unlock success" },
   { id: 85, name: "Palm vein unlock success" },
   { id: 86, name: "Lock with palm vein" },
   { id: 88, name: "Palm vein unlock failed - expired or ineffective" },
   { id: 91, name: "Failed to unlock with IC card" },
   { id: 92, name: "Administrator password to unlock" },
];
