const state = {
   user: null,
};

const mutations = {};

import axios from "../axios";
const actions = {
   async getAll({ commit }, params) {
      return await axios.get('/booking/getAllBooking', { params: params })

      return [
         {
            Id: 1,
            OwnerId: 1,
            UserId: 1,
            Code: "1295739",
            Status: 1,
            Note: "",
            Discount: 0,
            SubTotal: 140000,
            Total: 160000,
            CreatedOn: new Date(),
            UpdatedOn: null,
            UpdatedBy: null,
            Users: {
               Id: 1,
               Email: "user@mail.com",
               PhoneNumber: "+62818563874",
               Name: "Nama User",
               ProvinceId: 1,
               CityId: 1,
               BirthDate: null,
            },
            BookDetailCharges: [
               {
                  Id: 1,
                  OwnerId: 1,
                  BookId: 1,
                  BookDetailId: 1,
                  RoomChargeId: 1,
                  Total: 20000,
                  CreatedOn: new Date(),
                  CreatedBy: 1,
                  UpdatedOn: null,
                  UpdatedBy: null,
                  RoomCharges: {
                     Id: 1,
                     OwnerId: 1,
                     RoomId: 1,
                     RoomTypeId: 1,
                     ChargId: 1,
                     Type: 1,
                     Amount: 20000,
                     CreatedOn: new Date(),
                     CreatedBy: null,
                     Charges: {
                        Id: 1,
                        OwnerId: 1,
                        Name: "Extra Soft",
                        Type: 1,
                        Amount: 20000,
                        Description: "Extra soft",
                        CreatedOn: new Date(),
                        CreatedBy: 1,
                        UpdatedOn: null,
                        UpdatedBy: null,
                     },
                  },
               },
               {
                  Id: 2,
                  OwnerId: 1,
                  BookId: 1,
                  BookDetailId: 1,
                  RoomChargeId: 1,
                  Total: 20000,
                  CreatedOn: new Date(),
                  CreatedBy: 1,
                  UpdatedOn: null,
                  UpdatedBy: null,
                  RoomCharges: {
                     Id: 1,
                     OwnerId: 1,
                     RoomId: 1,
                     RoomTypeId: 1,
                     ChargId: 1,
                     Type: 1,
                     Amount: 20000,
                     CreatedOn: new Date(),
                     CreatedBy: null,
                     Charges: {
                        Id: 1,
                        OwnerId: 1,
                        Name: "Extra Hard",
                        Type: 1,
                        Amount: 20000,
                        Description: "Extra Mahal",
                        CreatedOn: new Date(),
                        CreatedBy: 1,
                        UpdatedOn: null,
                        UpdatedBy: null,
                     },
                  },
               },
            ],
            BookDetailAddOns: [],
            BookDetailDeposits: {
               Id: 1,
               OwnerId: 1,
               BookId: 1,
               BookDetailId: 1,
               RoomDepositId: 1,
               Total: 400000,
               CreatedOn: new Date(),
               CreatedBy: 1,
               UpdatedOn: null,
               UpdatedBy: null,
            },
            BookDetails: {
               Id: 1,
               OwnerId: 1,
               BookId: 1,
               UserId: 1,
               RoomId: 1,
               CheckIn: new Date(),
               CheckOut: new Date(new Date().setDate(new Date().getDate() + 1)),
               Pax: 2,
               Rooms: {
                  Id: 1,
                  OwnerId: 1,
                  PropertyId: 1,
                  RoomTypeId: 1,
                  Name: "Ruangan Super",
                  AliasName: "",
                  Code: "RS001",
                  TTLockId: "1285632",
                  Pax: 2,
                  SizeRoom: 24,
                  PaxChargeAmountType: 1,
                  PaxChargeAmount: 10000,
                  MaxAdditionalPax: 1,
                  CreatedOn: new Date(),
                  Createdby: 1,
                  UpdatedBy: null,
                  UpdatedOn: null,
                  RoomTypes: {
                     Id: 1,
                     OwnerId: 1,
                     PropertyId: 1,
                     Name: "Tipe",
                     AliasName: "",
                     Code: "RT RW",
                     AmountRoom: 1,
                     AmountPaxRoom: 2,
                     PaxChargeAmountType: 1,
                     PaxChargeAmount: 10000,
                     MaxAdditionalPax: 1,
                     OverChargeMinute: 20000,
                     SizeRoom: 24,
                     CreatedOn: new Date(),
                     CreatedBy: 1,
                     UpdatedOn: null,
                     UpdatedBy: null,
                  },
                  Property: {
                     Id: 1,
                     PropertyTypeId: 1,
                     OwnerId: 1,
                     Name: "Properti A",
                     ProvinceId: 1,
                     CityId: 1,
                     Status: 1,
                     Address: "Jl Situlah itu",
                     Description: "Apa kek",
                     SetByRoomType: 1,
                     Latitude: null,
                     Longitude: null,
                     HostedBy: 1,
                     CreatedOn: new Date(),
                     CreatedBy: 1,
                     UpdatedOn: null,
                     UpdatedBy: null,
                     Provinces: {
                        Id: 1,
                        OwnerId: 1,
                        Name: "Aceh",
                        CreatedOn: new Date(),
                        CreatedBy: 1,
                        UpdatedOn: null,
                        UpdatedBy: null,
                     },
                  },
               },
            },
            Payments: {
               Id: 1,
               OwnerId: 1,
               BookId: 1,
               UserId: 1,
               RoomId: 1,
               Type: 1,
               UsePoint: 0,
               SubTotal: 140000,
               Discount: 0,
               Total: 160000,
               CreatedOn: new Date(),
               UpdatedOn: null,
               UpdatedBy: null,
               PaymentDetails: {
                  Id: 1,
                  OwnerId: 1,
                  PaymentId: 1,
                  PaymentMethodId: 1,
                  PaymentMethods: {
                     Id: 1,
                     OwnerId: 1,
                     PaymentMethodTypeId: 1,
                     Name: "Credit BCA",
                     Code: "CC BCA",
                     ImageId: null,
                     Position: 1,
                     IsActive: 1,
                     CreatedOn: new Date(),
                     CreatedBy: 1,
                     UpdatedOn: null,
                     UpdatedBy: null,
                  },
                  Amount: 140000,
                  CreatedOn: new Date(),
                  CreatedBy: 1,
               },
            },
         },
      ];
      return await axios.get("/payment-method/getAll");
   },
   async create({ commit }, data) {
      return await axios.post("/payment-method", data);
   },
   async delete({ commit }, id) {
      return await axios.delete(`/payment-method/${id}`);
   },
   async update({ commit }, data) {
      return await axios.put(`/payment-method/${data.id}`, data);
   },
   async getById({ commit }, id) {
      return await axios.get(`/payment-method/${id}`);
   },
};

const getters = {
   user: (state) => state.user,
};

export default {
   namespaced: true,
   state,
   mutations,
   actions,
   getters,
};
